# docker-compose.yaml
version: '3'

services:
    centrifugo:
        container_name: centrifugo
        image: centrifugo/centrifugo:v3.0.5
        volumes:
            - ./docker/centrifugo.json:/centrifugo/config.json
        command: centrifugo -c config.json
        ports:
            - 8000:8000
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
        networks:
            - centrifugo_app


    centrifugo_app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: centrifugo_app
        tty: true
        expose:
            - 9000
        depends_on:
            - centrifugo_app_db
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - centrifugo_app

    centrifugo_app_nginx:
        image: nginx:stable
        container_name: centrifugo_app_nginx
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - centrifugo_app
        volumes:
            - ./:/var/www
            - ./docker/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - centrifugo_app

    centrifugo_app_db:
        image: postgres:12
        container_name: centrifugo_app_db
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5432:5432"
        networks:
            - centrifugo_app
volumes:
    db_data:

networks:
    centrifugo_app:
